# Generated by Django 3.0.3 on 2020-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(default='', max_length=50)),
                ('hospitaladd', models.CharField(default='', max_length=50)),
                ('hospitalphone', models.CharField(default='', max_length=50)),
                ('hospitalmap', models.CharField(default='', max_length=50)),
                ('hospitaltime', models.DateField(default='', max_length=50)),
                ('hospitalspecial', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
