# Generated by Django 3.0.3 on 2021-01-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
