# Generated by Django 3.1.1 on 2020-09-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedy',
            name='status',
        ),
    ]
