# Generated by Django 3.1.1 on 2020-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0003_auto_20200921_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Fitness',
        ),
    ]
