# Generated by Django 3.0.3 on 2020-09-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(default='', max_length=50)),
                ('hospitaladd', models.CharField(default='', max_length=50)),
                ('hospitalphone', models.CharField(default='', max_length=50)),
                ('hospitalmap', models.CharField(default='', max_length=50)),
                ('hospitaltime', models.DateField(default='', max_length=50)),
                ('hospitalspecial', models.CharField(default='', max_length=50)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.patient')),
            ],
        ),
    ]
