# Generated by Django 3.0.3 on 2020-09-23 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='patient',
        ),
        migrations.DeleteModel(
            name='rating_review',
        ),
    ]
