# Generated by Django 3.0.3 on 2020-09-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200923_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
