# Generated by Django 3.0.3 on 2020-12-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
