# Generated by Django 3.0.3 on 2021-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_doctor_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(default='', max_length=50)),
                ('hospitaladd', models.CharField(default='', max_length=50)),
                ('hospitalphone', models.CharField(default='', max_length=50)),
                ('hospitalmap', models.CharField(default='', max_length=50)),
                ('hospitaltime', models.DateField(default='', max_length=50)),
                ('hospitalspecial', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
