# Generated by Django 3.0.3 on 2021-01-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_contact_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
